tools:
  - class_name: "verl.tools.search_tool.SearchTool"
    config:
      retrieval_service_url: "http://10.63.234.28:8000/retrieve"
      topk: 5

      num_workers: 16
      rate_limit: 40
      timeout: 300
      type: native
    tool_schema:
      type: "function"
      function:
        name: "search"
        description: "Perform a search on a knowledge source. Returns top-5 hits with docid, score, and snippet. The snippet contains the document's contents (may be truncated based on token limits)."
        parameters:
          type: "object"
          properties:
            query:
              type: "string"
              description: "Search query string."
          required:
            - "query"
          additionalProperties: false

